export const prods=[
    {
     name:'Cyber Punk Model',
     price:3,
     category:'neon-solid',
     instruction:'Beautiful pale cyberpunk female with heavy black eyeliner, blue eyes, shaved side haircut, hyper detail, cinematic lighting, magic neon, dark red city –ar 9:16 –testp –upbeta',
     model:'chat-gpt',
     description:'"The scene unveils a stunning vision of a beautiful pale cyberpunk female, her features enhanced by heavy black eyeliner that accentuates her piercing blue eyes. She boldly flaunts a shaved side haircut, a daring choice that adds to her edgy appearance. The attention to detail in her cybernetic enhancements is remarkable, with hyper-realistic precision showcased in every aspect. Cinematic lighting casts dramatic shadows, emphasizing the contours of her face and augmenting her aura. The backdrop is a cityscape painted in dark red hues, as if immersed in eternal dusk. The streets are bathed in a magical neon glow, creating a mystical atmosphere that intertwines technology and enchantment',
     images:['Prompts/e8q6xhnsinymhyok6syq']
    } ,
    {
        name: "Nature's Resurgence",
        price: 3,
        category: "neon-solid",
        instruction: "earth reviving after human extinction, a new beginning, nature taking over buildings, animal kingdom, harmony, peace, earth balanced –version 3 –s 1250 –uplight –ar 4:3 –no text, blur",
        model: "midjourney",
        description: "Witness the Earth reviving after human extinction, symbolizing a new beginning. Nature takes over buildings, creating a harmonious and peaceful environment. The image showcases the balance of the Earth with elements such as the animal kingdom and lush greenery.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Sailing Serenity",
        price: 3,
        category: "neon-solid",
        instruction: "photo of an ultra-realistic sailing ship, dramatic light, pale sunrise, cinematic lighting, battered, low angle, trending on ArtStation, 4k, hyper-realistic, focused, extreme details, Unreal Engine 5, cinematic, masterpiece, art by Studio Ghibli, intricate artwork by John William Turner",
        model: "midjourney",
        description: "This ultra-realistic sailing ship photograph features dramatic lighting and a pale sunrise. The level of detail is remarkable, with intricate artwork reminiscent of Studio Ghibli and John William Turner. The artwork is currently trending on ArtStation.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Ornate Avian Beauty",
        price: 3,
        category: "neon-solid",
        instruction: "ethereal Bohemian Waxwing bird, Bombycilla garrulus :: intricate details, ornate, detailed illustration, octane render :: Johanna Rupprecht style, William Morris style :: trending on ArtStation –ar 9:16",
        model: "midjourney",
        description: "Behold the ethereal Bohemian Waxwing bird, intricately detailed with ornate features. The illustration showcases the unique style of Johanna Rupprecht and William Morris. This artwork is currently trending on ArtStation.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Futuristic Urbanscape",
        price: 3,
        category: "neon-solid",
        instruction: "Create an image of a futuristic city skyline at night, with a focus on advanced transportation systems and towering skyscrapers. Incorporate elements such as drones, flying cars, and high-speed trains.",
        model: "stable-diffusion",
        description: "Immerse yourself in a futuristic city skyline at night, characterized by advanced transportation systems and towering skyscrapers. The image incorporates elements such as drones, flying cars, and high-speed trains.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Apocalyptic Wasteland",
        price: 3,
        category: "north-hatchback",
        instruction: "Generate an image of a post-apocalyptic landscape, featuring a mix of natural and man-made elements. Include crumbling buildings, overgrown vegetation, and a sense of danger and abandonment.",
        model: "stable-diffusion",
        description: "Step into a post-apocalyptic landscape where nature and man-made structures coexist. Witness crumbling buildings, overgrown vegetation, and an atmosphere of danger and abandonment.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Dreamlike Forest",
        price: 3,
        category: "north-hatchback",
        instruction: "Create a surrealist image of a dreamlike forest, featuring twisted trees, floating islands, and otherworldly creatures. Use vibrant colors and an ethereal atmosphere to evoke a sense of mystery and wonder.",
        model: "stable-diffusion",
        description: "Immerse yourself in a surrealist depiction of a dreamlike forest. The image features twisted trees, floating islands, and otherworldly creatures. Vibrant colors and an ethereal atmosphere create a sense of mystery and wonder.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Cyberpunk Metropolis",
        price: 3,
        category: "north-hatchback",
        instruction: "Generate an image of a cyberpunk-inspired metropolis, featuring neon lights, holographic advertisements, and a bustling, futuristic atmosphere. Incorporate elements such as augmented reality interfaces, advanced robotics, and cybernetic enhancements.",
        model: "stable-diffusion",
        description: "Step into a cyberpunk-inspired metropolis teeming with life. Neon lights, holographic advertisements, and a futuristic atmosphere set the stage. The image incorporates elements such as augmented reality interfaces, advanced robotics, and cybernetic enhancements.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Space Suit Fantasy",
        price: 3,
        category: "north-hatchback",
        instruction: "space suit with boots, futuristic, character design, cinematic lightning, epic fantasy, hyper realistic, detail 8k –ar 9:16",
        model: "stable-diffusion",
        description: "Experience a futuristic space suit complete with boots. The image showcases a captivating character design with cinematic lightning and an epic fantasy feel. The level of detail is hyper-realistic, perfect for immersing yourself in the scene.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Surreal Underwater World",
        price: 3,
        category: "north-hatchback",
        instruction: "Create an image of a surreal underwater world, featuring strange sea creatures, coral reefs, and otherworldly landscapes. Use vibrant colors and an ethereal atmosphere to evoke a sense of mystery and wonder.",
        model: "stable-diffusion",
        description: "Dive into a surreal underwater world filled with strange sea creatures, mesmerizing coral reefs, and otherworldly landscapes. Vibrant colors and an ethereal atmosphere evoke a sense of mystery and wonder.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Post-Apocalyptic Cityscape",
        price: 3,
        category: "country-models",
        instruction: "Generate an image of a post-apocalyptic city, featuring crumbling buildings, overgrown vegetation, and a sense of danger and abandonment. Incorporate elements such as advanced robotics, cybernetic enhancements, and advanced transportation systems.",
        model: "stable-diffusion",
        description: "Explore a post-apocalyptic cityscape where crumbling buildings and overgrown vegetation dominate the landscape. The image captures a sense of danger and abandonment, enhanced by the inclusion of advanced robotics, cybernetic enhancements, and advanced transportation systems.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Mystical Forest Guardian",
        price: 3,
        category: "country-models",
        instruction: "Create an image of a mystical forest guardian, an ancient and powerful being that protects the forest from harm. Use vibrant colors, intricate details, and an ethereal atmosphere to capture the guardian's majestic presence.",
        model: "stable-diffusion",
        description: "Encounter a mystical forest guardian, an ancient and powerful being dedicated to protecting the forest from harm. The image showcases vibrant colors, intricate details, and an ethereal atmosphere that captures the guardian's majestic presence.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Retro Cyberpunk",
        price: 3,
        category: "country-models",
        instruction: "Create a retro-inspired cyberpunk scene, featuring neon lights, futuristic technology, and a gritty, dystopian atmosphere. Incorporate elements such as old-school computer interfaces, analog machinery, and vintage fashion.",
        model: "stable-diffusion",
        description: "Immerse yourself in a retro-inspired cyberpunk scene, where neon lights illuminate a gritty and dystopian atmosphere. The image incorporates elements such as old-school computer interfaces, analog machinery, and vintage fashion, capturing the essence of a bygone era.",
        images:['Prompts/e8q6xhnsinymhyok6syq'],
      },
      {
        name: "Portrait of an Asian Old Warrior Chief",
        price: 3,
        category: "country-models",
        instruction: "Portrait photo of an Asia old warrior chief, tribal panther make up, blue on red, side profile, looking away, serious eyes, 50mm portrait photography, hard rim lighting photography–beta –ar 2:3 –beta –upbeta",
        model: "stable-diffusion",
        description: "Capture the essence of an Asian old warrior chief in a portrait photo. The chief is adorned with tribal panther makeup and is captured in a side profile, looking away with serious eyes. The photo is taken using a 50mm lens and features hard rim lighting, adding a dramatic effect to the composition.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Rubber Duck Aliens Visiting Earth",
        price: 3,
        category: "country-models",
        instruction: "Rubber Duck Aliens visiting the Earth for the first time, hyper-realistic, cinematic, detailed –ar 16:9",
        model: "stable-diffusion",
        description: "Witness the first visit of hyper-realistic Rubber Duck Aliens to Earth. The image captures the aliens in cinematic detail, creating a sense of realism and wonder. The composition is presented in a 16:9 aspect ratio, adding to the cinematic appeal.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Reunion of Man Team Squad",
        price: 3,
        category: "neon-solid",
        instruction: "Reunion of man, team, squad, cyberpunk, abstract, full hd render + 3d octane render +4k UHD + immense detail + dramatic lighting + well lit + black, purple, blue, pink, cerulean, teal, metallic colours, + fine details + octane render + 8k",
        model: "stable-diffusion",
        description: "Experience the reunion of a man, team, and squad in a cyberpunk-inspired setting. The image features an abstract composition rendered in full HD, 4K UHD, and immense detail. Dramatic lighting enhances the scene, while the use of black, purple, blue, pink, cerulean, teal, and metallic colors adds vibrancy. Fine details and an octane render create a visually stunning 8K image.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Ultra Photoreal Concept Art",
        price: 3,
        category: "neon-solid",
        instruction: "ultra photoreal , photographic, concept art, cinematic lighting, cinematic composition, rule of thirds , mysterious, eerie, cinematic lighting, ultra-detailed, ultrarealistic, photorealism, 8k, octane render",
        model: "stable-diffusion",
        description: "Immerse yourself in the world of ultra photorealistic concept art. The image captures a cinematic composition with rule of thirds, featuring mysterious and eerie elements. Cinematic lighting enhances the atmosphere, while ultra-detailed and ultrarealistic elements create a sense of photorealism. The image is rendered in 8K using octane render, providing stunning visual fidelity.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Monet's Water Lilies",
        price: 3,
        category: "neon-solid",
        instruction: "Generate an image in the style of Monet’s Water Lilies, featuring vibrant colors and a focus on the interplay of light and color. The image should be at least 4000×2500 pixels in size and include details such as reflections and ripples in the water to enhance the realism of the scene.",
        model: "stable-diffusion",
        description: "Immerse yourself in the enchanting world of Monet's Water Lilies. The image showcases vibrant colors and the interplay of light and color, capturing the essence of Monet's iconic style. With a size of at least 4000x2500 pixels, the image includes intricate details such as reflections and ripples in the water, enhancing the realism and beauty of the scene.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "AI-Generated Oil Painting Portrait",
        price: 3,
        category: "dalle",
        instruction: "Create an AI-generated oil painting of a portrait, featuring a range of skin tones and realistic textures to convey a sense of humanity. The painting should be at least 3000×2000 pixels in size and include details such as brushstrokes and layering to mimic the techniques of traditional oil painting.",
        model: "chat-gpt",
        description: "Experience the beauty of an AI-generated oil painting portrait. The painting captures a range of skin tones and realistic textures, evoking a sense of humanity. With a size of at least 3000x2000 pixels, the painting includes intricate details such as brushstrokes and layering, mimicking the techniques of traditional oil painting.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Salvador Dali's Melting Clocks",
        price: 3,
        category: "dalle",
        instruction: "Generate an image in the style of Salvador Dali’s melting clocks, featuring surreal elements and a focus on the manipulation of time and space. The image should be at least 4000×2500 pixels in size and include details such as dynamic lighting and movement to enhance the surreal atmosphere.",
        model: "chat-gpt",
        description: "Enter the realm of Salvador Dali's melting clocks in this surreal image. The composition features surreal elements and explores the manipulation of time and space. With a size of at least 4000x2500 pixels, the image includes details such as dynamic lighting and movement, enhancing the surreal atmosphere and transporting you to Dali's extraordinary world.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "AI-Generated Mixed Media Painting",
        price: 3,
        category: "dalle",
        instruction: "Create an AI-generated mixed media painting that combines elements of photography, collage, and painting to create a unique and dynamic image. The painting should be at least 3000×2000 pixels in size and include a range of colors, textures, and techniques to create a sense of depth and complexity.",
        model: "chat-gpt",
        description: "Embark on a journey into the world of mixed media art with this AI-generated painting. The image combines elements of photography, collage, and painting, resulting in a unique and dynamic composition. With a size of at least 3000x2000 pixels, the painting showcases a range of colors, textures, and techniques, creating a sense of depth and complexity that will captivate your imagination.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Frida Kahlo Inspired Self-Portrait",
        price: 3,
        category: "dalle",
        instruction: "Generate an image in the style of Frida Kahlo’s self-portraits, featuring vibrant colors and a focus on self-expression and identity. The image should be at least 4000×2500 pixels in size and include details such as brushstrokes and symbols that evoke the style of the original artist.",
        model: "chat-gpt",
        description: "Experience the spirit of Frida Kahlo's self-portraits in this AI-generated image. Inspired by her vibrant colors and focus on self-expression and identity, the image captures the essence of Kahlo's unique style. With a size of at least 4000x2500 pixels, the image includes intricate details such as brushstrokes and symbols that evoke the artistic language of Frida Kahlo.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Wildly Futuristic Clothing",
        price: 3,
        category: "dalle",
        instruction: "Create wildly futuristic clothing with glowing and colorful decoration",
        model: "chat-gpt",
        description: "Step into the future with wildly futuristic clothing adorned with glowing and colorful decorations. These avant-garde designs push the boundaries of fashion, combining innovative materials, striking shapes, and vibrant colors. Prepare to turn heads and make a bold statement with these cutting-edge fashion creations.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Charcuterie Board with Multicolored Alien Cheeses",
        price: 3,
        category: "dalle",
        instruction: "Charcuterie board with multicolored alien cheeses, with glowing mold and fungus",
        model: "chat-gpt",
        description: "Indulge in an otherworldly culinary experience with a charcuterie board featuring multicolored alien cheeses. These extraordinary cheeses are adorned with glowing molds and fungi, creating an ethereal and mesmerizing display. Delight your taste buds and embark on a gastronomic adventure like no other with this alien-inspired charcuterie board.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Breathtaking Detailed Concept Art Painting",
        price: 3,
        category: "dalle",
        instruction: "Breathtaking detailed concept art painting art deco pattern – blue flowers with anxious piercing eyes and blend of flowers and birds, by Hsiao-Ron Cheng and John James Audubon, bizarre compositions, exquisite detail, extremely moody lighting, 8K",
        model: "chat-gpt",
        description: "Immerse yourself in a breathtakingly detailed concept art painting that combines an art deco pattern with blue flowers, anxious piercing eyes, and a blend of flowers and birds. Inspired by the works of Hsiao-Ron Cheng and John James Audubon, this painting features bizarre compositions, exquisite detail, and extremely moody lighting. With a resolution of 8K, every brushstroke and nuance comes to life, inviting you into a world of beauty and intrigue.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "Woman Wearing a Strapless Black Top",
        price: 3,
        category: "strategist-virtual",
        instruction: "Woman wearing a strapless black top + eye contact + full body pose arms crossed on her chest + blonde hair and dark-green eyes + candlelight and intimate setting + oil painting style + lots of detail + very detailed shadows",
        model: "chat-gpt",
        description: "Discover the allure of a woman wearing a strapless black top in an intimate and captivating setting. With eye contact and a full body pose, her arms are crossed on her chest. The woman features blonde hair and mesmerizing dark-green eyes. Set in candlelight, this scene is rendered in an oil painting style with meticulous attention to detail, including very detailed shadows that add depth and realism to the composition.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      },
      {
        name: "3D Isometric Element on a Base",
        price: 3,
        category: "strategist-virtual",
        instruction: "[Link to an image of reference (you can find them in Google images -> copy + paste], 3D isometric [Element you want] on a [the base you want] with a [color]",
        model: "chat-gpt",
        description: "Bring your imagination to life with a 3D isometric element on a customized base. Based on the reference image you provide, the 3D element will be meticulously crafted to your specifications. Choose the desired base and color to create a unique and visually striking composition that will captivate viewers.",
        images:['Prompts/e8q6xhnsinymhyok6syq']
      }
]